my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls"))
]

polls/urls.py
from django.urls import path
from . import views


app_name = "polls"
urlpatterns = [
    #ex : /polls/
    #function view
    # path("", views.index, name="index"),
    #class view
    path("", views.IndexView.as_view(), name="index"),
    #ex : /polls/5/
    #function view
    # path("<int:question_id>/", views.detail , name="details"),
    #class view
    path("<int:pk>/", views.DetailView.as_view(), name="details"),
    #ex : /polls/5/results/
    #function view
    # path("<int:question_id>/results", views.results , name="results"),
    #class view
    path("<int:pk>/results", views.ResultsView.as_view(), name="results"),
    #ex : /polls/5/vote/
    path("<int:question_id>/vote", views.vote , name="votes")
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=256)
    pub_date      = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=256)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice

'''

def index(request):
    latest_question_list = Question.objects.filter()
    return render(request, "polls/index.html/", {
        "latest_question_list" : latest_question_list
    }) 
    # return HttpResponse("Estás en la página principal de la App")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {
        "question" : question
    })

    # return HttpResponse(f"Estás viendo la pregunta número {question_id}")


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {
        "question": question
    })
    # return HttpResponse(f"Estás viendo los resultados de la pregunta número {question_id}")


'''

#vistas basadas en clases

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        '''Return the last five published questions'''
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    queryset = Question.objects.all()
    model: Question
    template_name= "polls/detail.html"

    def get_queryset(self):
        '''Excludes any questions that are not published yet'''
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    queryset = Question.objects.all()
    model: Question
    template_name= "polls/results.html"

#vistas basadas en funciones

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id )
    try:
        selected_choice = question.choice_set.get(pk= request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "No elegiste una respuesta"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
        # return HttpResponse(f"Estás votando a la pregunta número {question_id}")

# Create your views here.

polls/templates/polls/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'polls/style.css' %}">
    <link rel="stylesheet" href=" {% static 'polls/detail.css' %}">
    <title>{{ question.questio_text }}</title>
</head>
<body>

    <form action="{% url 'polls:votes' question.id %}" method="post" > 
        {% csrf_token %}    
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
            {% endif %}
            {% for choice in question.choice_set.all  %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Votar">
    </form>

</body>
</html>

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'polls/reset.css' %}">
    <link rel="stylesheet" href=" {% static 'polls/style.css' %}">
    <title>Premios Platzi App</title>
</head>
<body>
    <header>
        <h1>Premios Platzi App</h1>
    </header>
    <main>
        {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list  %}
                    <li> <a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a> </li>
                {% endfor %}
            </ul>
        {% else %}
            <p> No existen encuestas </p>
    
        {% endif %}
    </main>
    <footer>
        <a href="https://platzi.com">Platzi</a>
        <a href="#">Contacto</a>
        <a href="#">Quieres ser profe?</a>
        <a href="#">Politica de privacidad</a>
        <a href="#">Términos y condiciones</a>
    </footer>




</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all  %}
        <li>{{ choice.choice_text }} -- {{ choice.votes}} voto{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:details' question.id %}">Te gustaría votar de nuevo?</a>